name: Test jenkins-dsl/agent-install.sh

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    test-agent-install:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout cassandra-builds
            uses: actions/checkout@v3
          - name: Test agent-install.sh
            working-directory: jenkins-dsl
            run: docker run --cap-add net_raw --cap-add sys_admin -v `pwd`:/jenkin-dsl ubuntu:24.04 bash -e -o pipefail /jenkin-dsl/agent-install.sh
